---
- name: Deploy Nginx LetsEncrypt Grafana
  hosts: nginx
  vars:
    subnet: 172.20.0.0/24
    agent_name: "VM1"
    agent_tags: "Nginx"
    agent_provider: "13" # <----Choose your Provider - https://docs.syntropystack.com/docs/syntropy-agent-variables
    domain_dns: "DomainDNS" # <----Your Domain DNS
    email: "Email" # <----Your EMail
    login_grafana: "Login" # <----Choose your login
    pass_grafana: "Password" # <----Choose your Password
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - launch_nginx

- name: Deploy Prometheus
  hosts: prometheus
  vars:
    subnet: 172.21.0.0/24
    agent_name: "VM2"
    agent_tags: "Prometheus"
    agent_provider: "5" # <----Choose your Provider - https://docs.syntropystack.com/docs/syntropy-agent-variables
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - launch_prometheus

- name: Deploy Node_Exporter
  hosts: node-exporter
  vars:
    subnet: 172.22.0.0/24
    agent_name: "VM3"
    agent_tags: "Node-Exporter"
    agent_provider: "2" # <----Choose your Provider - https://docs.syntropystack.com/docs/syntropy-agent-variables
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - launch_node_exporter
